# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2020.3\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2020.3\bin\cmake\win\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = \Users\MONTER\Documents\primitive

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\MONTER\Documents\primitive

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.3\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.3\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\MONTER\Documents\primitive\CMakeFiles C:\Users\MONTER\Documents\primitive\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\MONTER\Documents\primitive\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named primitive

# Build rule for target.
primitive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) primitive
.PHONY : primitive

# fast build rule for target.
primitive\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\build
.PHONY : primitive\fast

include\imgui\examples\imgui_impl_glfw.obj: include\imgui\examples\imgui_impl_glfw.cpp.obj

.PHONY : include\imgui\examples\imgui_impl_glfw.obj

# target to build an object file
include\imgui\examples\imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\examples\imgui_impl_glfw.cpp.obj
.PHONY : include\imgui\examples\imgui_impl_glfw.cpp.obj

include\imgui\examples\imgui_impl_glfw.i: include\imgui\examples\imgui_impl_glfw.cpp.i

.PHONY : include\imgui\examples\imgui_impl_glfw.i

# target to preprocess a source file
include\imgui\examples\imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\examples\imgui_impl_glfw.cpp.i
.PHONY : include\imgui\examples\imgui_impl_glfw.cpp.i

include\imgui\examples\imgui_impl_glfw.s: include\imgui\examples\imgui_impl_glfw.cpp.s

.PHONY : include\imgui\examples\imgui_impl_glfw.s

# target to generate assembly for a file
include\imgui\examples\imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\examples\imgui_impl_glfw.cpp.s
.PHONY : include\imgui\examples\imgui_impl_glfw.cpp.s

include\imgui\examples\imgui_impl_opengl3.obj: include\imgui\examples\imgui_impl_opengl3.cpp.obj

.PHONY : include\imgui\examples\imgui_impl_opengl3.obj

# target to build an object file
include\imgui\examples\imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\examples\imgui_impl_opengl3.cpp.obj
.PHONY : include\imgui\examples\imgui_impl_opengl3.cpp.obj

include\imgui\examples\imgui_impl_opengl3.i: include\imgui\examples\imgui_impl_opengl3.cpp.i

.PHONY : include\imgui\examples\imgui_impl_opengl3.i

# target to preprocess a source file
include\imgui\examples\imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\examples\imgui_impl_opengl3.cpp.i
.PHONY : include\imgui\examples\imgui_impl_opengl3.cpp.i

include\imgui\examples\imgui_impl_opengl3.s: include\imgui\examples\imgui_impl_opengl3.cpp.s

.PHONY : include\imgui\examples\imgui_impl_opengl3.s

# target to generate assembly for a file
include\imgui\examples\imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\examples\imgui_impl_opengl3.cpp.s
.PHONY : include\imgui\examples\imgui_impl_opengl3.cpp.s

include\imgui\imgui.obj: include\imgui\imgui.cpp.obj

.PHONY : include\imgui\imgui.obj

# target to build an object file
include\imgui\imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui.cpp.obj
.PHONY : include\imgui\imgui.cpp.obj

include\imgui\imgui.i: include\imgui\imgui.cpp.i

.PHONY : include\imgui\imgui.i

# target to preprocess a source file
include\imgui\imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui.cpp.i
.PHONY : include\imgui\imgui.cpp.i

include\imgui\imgui.s: include\imgui\imgui.cpp.s

.PHONY : include\imgui\imgui.s

# target to generate assembly for a file
include\imgui\imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui.cpp.s
.PHONY : include\imgui\imgui.cpp.s

include\imgui\imgui_demo.obj: include\imgui\imgui_demo.cpp.obj

.PHONY : include\imgui\imgui_demo.obj

# target to build an object file
include\imgui\imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui_demo.cpp.obj
.PHONY : include\imgui\imgui_demo.cpp.obj

include\imgui\imgui_demo.i: include\imgui\imgui_demo.cpp.i

.PHONY : include\imgui\imgui_demo.i

# target to preprocess a source file
include\imgui\imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui_demo.cpp.i
.PHONY : include\imgui\imgui_demo.cpp.i

include\imgui\imgui_demo.s: include\imgui\imgui_demo.cpp.s

.PHONY : include\imgui\imgui_demo.s

# target to generate assembly for a file
include\imgui\imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui_demo.cpp.s
.PHONY : include\imgui\imgui_demo.cpp.s

include\imgui\imgui_draw.obj: include\imgui\imgui_draw.cpp.obj

.PHONY : include\imgui\imgui_draw.obj

# target to build an object file
include\imgui\imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui_draw.cpp.obj
.PHONY : include\imgui\imgui_draw.cpp.obj

include\imgui\imgui_draw.i: include\imgui\imgui_draw.cpp.i

.PHONY : include\imgui\imgui_draw.i

# target to preprocess a source file
include\imgui\imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui_draw.cpp.i
.PHONY : include\imgui\imgui_draw.cpp.i

include\imgui\imgui_draw.s: include\imgui\imgui_draw.cpp.s

.PHONY : include\imgui\imgui_draw.s

# target to generate assembly for a file
include\imgui\imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui_draw.cpp.s
.PHONY : include\imgui\imgui_draw.cpp.s

include\imgui\imgui_widgets.obj: include\imgui\imgui_widgets.cpp.obj

.PHONY : include\imgui\imgui_widgets.obj

# target to build an object file
include\imgui\imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui_widgets.cpp.obj
.PHONY : include\imgui\imgui_widgets.cpp.obj

include\imgui\imgui_widgets.i: include\imgui\imgui_widgets.cpp.i

.PHONY : include\imgui\imgui_widgets.i

# target to preprocess a source file
include\imgui\imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui_widgets.cpp.i
.PHONY : include\imgui\imgui_widgets.cpp.i

include\imgui\imgui_widgets.s: include\imgui\imgui_widgets.cpp.s

.PHONY : include\imgui\imgui_widgets.s

# target to generate assembly for a file
include\imgui\imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\include\imgui\imgui_widgets.cpp.s
.PHONY : include\imgui\imgui_widgets.cpp.s

src\Camera.obj: src\Camera.cpp.obj

.PHONY : src\Camera.obj

# target to build an object file
src\Camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Camera.cpp.obj
.PHONY : src\Camera.cpp.obj

src\Camera.i: src\Camera.cpp.i

.PHONY : src\Camera.i

# target to preprocess a source file
src\Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Camera.cpp.i
.PHONY : src\Camera.cpp.i

src\Camera.s: src\Camera.cpp.s

.PHONY : src\Camera.s

# target to generate assembly for a file
src\Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Camera.cpp.s
.PHONY : src\Camera.cpp.s

src\Collider.obj: src\Collider.cpp.obj

.PHONY : src\Collider.obj

# target to build an object file
src\Collider.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Collider.cpp.obj
.PHONY : src\Collider.cpp.obj

src\Collider.i: src\Collider.cpp.i

.PHONY : src\Collider.i

# target to preprocess a source file
src\Collider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Collider.cpp.i
.PHONY : src\Collider.cpp.i

src\Collider.s: src\Collider.cpp.s

.PHONY : src\Collider.s

# target to generate assembly for a file
src\Collider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Collider.cpp.s
.PHONY : src\Collider.cpp.s

src\Core.obj: src\Core.cpp.obj

.PHONY : src\Core.obj

# target to build an object file
src\Core.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Core.cpp.obj
.PHONY : src\Core.cpp.obj

src\Core.i: src\Core.cpp.i

.PHONY : src\Core.i

# target to preprocess a source file
src\Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Core.cpp.i
.PHONY : src\Core.cpp.i

src\Core.s: src\Core.cpp.s

.PHONY : src\Core.s

# target to generate assembly for a file
src\Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Core.cpp.s
.PHONY : src\Core.cpp.s

src\Game.obj: src\Game.cpp.obj

.PHONY : src\Game.obj

# target to build an object file
src\Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Game.cpp.obj
.PHONY : src\Game.cpp.obj

src\Game.i: src\Game.cpp.i

.PHONY : src\Game.i

# target to preprocess a source file
src\Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Game.cpp.i
.PHONY : src\Game.cpp.i

src\Game.s: src\Game.cpp.s

.PHONY : src\Game.s

# target to generate assembly for a file
src\Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Game.cpp.s
.PHONY : src\Game.cpp.s

src\Input.obj: src\Input.cpp.obj

.PHONY : src\Input.obj

# target to build an object file
src\Input.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Input.cpp.obj
.PHONY : src\Input.cpp.obj

src\Input.i: src\Input.cpp.i

.PHONY : src\Input.i

# target to preprocess a source file
src\Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Input.cpp.i
.PHONY : src\Input.cpp.i

src\Input.s: src\Input.cpp.s

.PHONY : src\Input.s

# target to generate assembly for a file
src\Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Input.cpp.s
.PHONY : src\Input.cpp.s

src\Mesh.obj: src\Mesh.cpp.obj

.PHONY : src\Mesh.obj

# target to build an object file
src\Mesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Mesh.cpp.obj
.PHONY : src\Mesh.cpp.obj

src\Mesh.i: src\Mesh.cpp.i

.PHONY : src\Mesh.i

# target to preprocess a source file
src\Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Mesh.cpp.i
.PHONY : src\Mesh.cpp.i

src\Mesh.s: src\Mesh.cpp.s

.PHONY : src\Mesh.s

# target to generate assembly for a file
src\Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Mesh.cpp.s
.PHONY : src\Mesh.cpp.s

src\Model.obj: src\Model.cpp.obj

.PHONY : src\Model.obj

# target to build an object file
src\Model.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Model.cpp.obj
.PHONY : src\Model.cpp.obj

src\Model.i: src\Model.cpp.i

.PHONY : src\Model.i

# target to preprocess a source file
src\Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Model.cpp.i
.PHONY : src\Model.cpp.i

src\Model.s: src\Model.cpp.s

.PHONY : src\Model.s

# target to generate assembly for a file
src\Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Model.cpp.s
.PHONY : src\Model.cpp.s

src\Shader.obj: src\Shader.cpp.obj

.PHONY : src\Shader.obj

# target to build an object file
src\Shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Shader.cpp.obj
.PHONY : src\Shader.cpp.obj

src\Shader.i: src\Shader.cpp.i

.PHONY : src\Shader.i

# target to preprocess a source file
src\Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Shader.cpp.i
.PHONY : src\Shader.cpp.i

src\Shader.s: src\Shader.cpp.s

.PHONY : src\Shader.s

# target to generate assembly for a file
src\Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Shader.cpp.s
.PHONY : src\Shader.cpp.s

src\Sound.obj: src\Sound.cpp.obj

.PHONY : src\Sound.obj

# target to build an object file
src\Sound.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Sound.cpp.obj
.PHONY : src\Sound.cpp.obj

src\Sound.i: src\Sound.cpp.i

.PHONY : src\Sound.i

# target to preprocess a source file
src\Sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Sound.cpp.i
.PHONY : src\Sound.cpp.i

src\Sound.s: src\Sound.cpp.s

.PHONY : src\Sound.s

# target to generate assembly for a file
src\Sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Sound.cpp.s
.PHONY : src\Sound.cpp.s

src\Texture.obj: src\Texture.cpp.obj

.PHONY : src\Texture.obj

# target to build an object file
src\Texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Texture.cpp.obj
.PHONY : src\Texture.cpp.obj

src\Texture.i: src\Texture.cpp.i

.PHONY : src\Texture.i

# target to preprocess a source file
src\Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Texture.cpp.i
.PHONY : src\Texture.cpp.i

src\Texture.s: src\Texture.cpp.s

.PHONY : src\Texture.s

# target to generate assembly for a file
src\Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Texture.cpp.s
.PHONY : src\Texture.cpp.s

src\Window.obj: src\Window.cpp.obj

.PHONY : src\Window.obj

# target to build an object file
src\Window.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Window.cpp.obj
.PHONY : src\Window.cpp.obj

src\Window.i: src\Window.cpp.i

.PHONY : src\Window.i

# target to preprocess a source file
src\Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Window.cpp.i
.PHONY : src\Window.cpp.i

src\Window.s: src\Window.cpp.s

.PHONY : src\Window.s

# target to generate assembly for a file
src\Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\Window.cpp.s
.PHONY : src\Window.cpp.s

src\externalModel.obj: src\externalModel.cpp.obj

.PHONY : src\externalModel.obj

# target to build an object file
src\externalModel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\externalModel.cpp.obj
.PHONY : src\externalModel.cpp.obj

src\externalModel.i: src\externalModel.cpp.i

.PHONY : src\externalModel.i

# target to preprocess a source file
src\externalModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\externalModel.cpp.i
.PHONY : src\externalModel.cpp.i

src\externalModel.s: src\externalModel.cpp.s

.PHONY : src\externalModel.s

# target to generate assembly for a file
src\externalModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\externalModel.cpp.s
.PHONY : src\externalModel.cpp.s

src\main.obj: src\main.cpp.obj

.PHONY : src\main.obj

# target to build an object file
src\main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\main.cpp.obj
.PHONY : src\main.cpp.obj

src\main.i: src\main.cpp.i

.PHONY : src\main.i

# target to preprocess a source file
src\main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\main.cpp.i
.PHONY : src\main.cpp.i

src\main.s: src\main.cpp.s

.PHONY : src\main.s

# target to generate assembly for a file
src\main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\primitive.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\primitive.dir\src\main.cpp.s
.PHONY : src\main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... primitive
	@echo ... include/imgui/examples/imgui_impl_glfw.obj
	@echo ... include/imgui/examples/imgui_impl_glfw.i
	@echo ... include/imgui/examples/imgui_impl_glfw.s
	@echo ... include/imgui/examples/imgui_impl_opengl3.obj
	@echo ... include/imgui/examples/imgui_impl_opengl3.i
	@echo ... include/imgui/examples/imgui_impl_opengl3.s
	@echo ... include/imgui/imgui.obj
	@echo ... include/imgui/imgui.i
	@echo ... include/imgui/imgui.s
	@echo ... include/imgui/imgui_demo.obj
	@echo ... include/imgui/imgui_demo.i
	@echo ... include/imgui/imgui_demo.s
	@echo ... include/imgui/imgui_draw.obj
	@echo ... include/imgui/imgui_draw.i
	@echo ... include/imgui/imgui_draw.s
	@echo ... include/imgui/imgui_widgets.obj
	@echo ... include/imgui/imgui_widgets.i
	@echo ... include/imgui/imgui_widgets.s
	@echo ... src/Camera.obj
	@echo ... src/Camera.i
	@echo ... src/Camera.s
	@echo ... src/Collider.obj
	@echo ... src/Collider.i
	@echo ... src/Collider.s
	@echo ... src/Core.obj
	@echo ... src/Core.i
	@echo ... src/Core.s
	@echo ... src/Game.obj
	@echo ... src/Game.i
	@echo ... src/Game.s
	@echo ... src/Input.obj
	@echo ... src/Input.i
	@echo ... src/Input.s
	@echo ... src/Mesh.obj
	@echo ... src/Mesh.i
	@echo ... src/Mesh.s
	@echo ... src/Model.obj
	@echo ... src/Model.i
	@echo ... src/Model.s
	@echo ... src/Shader.obj
	@echo ... src/Shader.i
	@echo ... src/Shader.s
	@echo ... src/Sound.obj
	@echo ... src/Sound.i
	@echo ... src/Sound.s
	@echo ... src/Texture.obj
	@echo ... src/Texture.i
	@echo ... src/Texture.s
	@echo ... src/Window.obj
	@echo ... src/Window.i
	@echo ... src/Window.s
	@echo ... src/externalModel.obj
	@echo ... src/externalModel.i
	@echo ... src/externalModel.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

